baseURL = "http://insideout.top/"
languageCode = "zh"
title = "insideout"
copyright = "2014 - 2020 Chang"
theme = "diary"
googleAnalytics = "UA-51193598-1"
disqusShortname = "insideout-top"
[params]
subtitle = ".top"
enableGitalk = false
favicon = "/favicon.ico"

[frontmatter]
date  = [":filename", ":default"]

[permalinks]
  posts = "/:year/:month/:day/:slug/"

[params.gitalk]
  owner = "user"
  repo = "repo name"
  client_id = "your client id"
  client_secret = "your client secret"
[taxonomies]
   tag = "tags"
   category = "categories"

[[menu.main]]
url = "/posts"
name = "Blog"
weight = 1
[[menu.main]]
url = "/categories"
name = "Categories"
weight = 2
[[menu.main]]
url = "/links"
name = "Links"
weight = 3
[[menu.main]]
url = "/instagram"
name = "ins"
weight = 4
[[menu.main]]
url = "/about"
name = "About"
weight = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
