baseURL = "https://insideout.top/"
languageCode = "zh"
title = "insideout"
copyright = "2014 - 2026, All Rights Reserved"
theme = "diary"
googleAnalytics = "UA-51193598-1"
disqusShortname = "insideout-top"
# 确保分页大小是正整数（比如10），这是翻页功能的基础
paginate = 10
# 可选：指定博客文章的主分区（确保首页/列表页能正确获取文章）
mainSections = ["posts"]
# 补充作者配置，解决RSS模板报错

[Author]
  name = "insideout"
  email = "i@insideout.top"  

[params]
subtitle = ".top"
enableGitalk = false
favicon = "/favicon.ico"

[frontmatter]
date  = [":filename", ":default"]
[permalinks]
  posts = "/:year/:month/:day/:slug/"

[params.gitalk]
  owner = "user"
  repo = "repo name"
  client_id = "your client id"
  client_secret = "your client secret"
[taxonomies]
   tag = "tags"
   category = "categories"

[[menu.main]]
url = "/posts"
name = "Blog"
weight = 1
[[menu.main]]
url = "/categories"
name = "Categories"
weight = 2
[[menu.main]]
url = "/links"
name = "Links"
weight = 3
[[menu.main]]
url = "/about"
name = "About"
weight = 4

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "manni"
    tabWidth = 4
